### ISSUE TITLE
Add Helm chart (re-)generation as pre-commit hook

### ISSUE THREAD

**Issue by Techassi** [stackabletech/operator-templating#263]
This issue tracks the implementation of Helm chart (re-)generation using a pre-commit hook. This hook will make sure that each commit of a PR checks in an up-to-date chart version. If we are confident enough, we could eventually remove the step in our GitHub workflow.

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/operator-templating/pull/264
- [ ] https://github.com/stackabletech/operator-templating/pull/266
```

```[tasklist]
### Merge Downstream PRs
- [ ] https://github.com/stackabletech/airflow-operator/pull/297
- [ ] https://github.com/stackabletech/commons-operator/pull/166
- [ ] https://github.com/stackabletech/druid-operator/pull/451
- [ ] https://github.com/stackabletech/hbase-operator/pull/374
- [ ] https://github.com/stackabletech/hdfs-operator/pull/371
- [ ] https://github.com/stackabletech/hello-world-operator/pull/17
- [ ] https://github.com/stackabletech/hive-operator/pull/353
- [ ] https://github.com/stackabletech/kafka-operator/pull/603
- [ ] https://github.com/stackabletech/nifi-operator/pull/484
- [ ] https://github.com/stackabletech/listener-operator/pull/89
- [ ] https://github.com/stackabletech/opa-operator/pull/459
- [ ] https://github.com/stackabletech/secret-operator/pull/293
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/257
- [ ] https://github.com/stackabletech/superset-operator/pull/382
- [ ] https://github.com/stackabletech/trino-operator/pull/442
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/703
```

```[tasklist]
### Optional Tasks
- [ ] Remove Chart Check Action Step
```

**Comment by Techassi** [comment]
One downstream PR is missing. It requires @nightkr input on the `default.nix` change.

**Comment by Techassi** [comment]
Reverted the changes in `secret-operator`. Issue #267 tracks the required code change in `operator-templating`.
