### ISSUE TITLE
chore: Update Rust toolchain to 1.80.0

### ISSUE THREAD

**Issue by Techassi** [stackabletech/operator-templating#415]
## Rust Toolchain Update to 1.80.0

Part of https://github.com/stackabletech/operator-rs/pull/827

### Update Rust Toolchain

```[tasklist]
### Tasks in this Repository
- [ ] https://github.com/stackabletech/operator-templating/pull/416
- [ ] https://github.com/stackabletech/docker-images/pull/794
- [x] Generate downstream PRs using the ["Generate Downstream PRs"](https://github.com/stackabletech/operator-templating/actions/workflows/generate_prs.yml) action.
- [x] Merge downstream PRs, see below for more details.
```

### Merge Downstream PRs

Replace the items in the task lists below with the applicable Pull Requests

```[tasklist]
### Tasks in Downstream Repositories
- [ ] https://github.com/stackabletech/airflow-operator/pull/478
- [ ] https://github.com/stackabletech/commons-operator/pull/273
- [ ] https://github.com/stackabletech/druid-operator/pull/604
- [ ] https://github.com/stackabletech/edc-operator/pull/117
- [ ] https://github.com/stackabletech/hbase-operator/pull/538
- [ ] https://github.com/stackabletech/hdfs-operator/pull/564
- [ ] https://github.com/stackabletech/hello-world-operator/pull/110
- [ ] https://github.com/stackabletech/hive-operator/pull/495
- [ ] https://github.com/stackabletech/kafka-operator/pull/740
- [ ] https://github.com/stackabletech/listener-operator/pull/215
- [ ] https://github.com/stackabletech/nifi-operator/pull/652
- [ ] https://github.com/stackabletech/opa-operator/pull/609
- [ ] https://github.com/stackabletech/secret-operator/pull/486
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/440
- [ ] https://github.com/stackabletech/superset-operator/pull/519
- [ ] https://github.com/stackabletech/trino-operator/pull/623
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/843
```
