### ISSUE TITLE
chore: Pre-release Rust toolchain and pre-commit updates

### ISSUE THREAD

**Issue by Techassi** [stackabletech/operator-templating#450]
## Pre-Release Updates for Stackable Release 24.11

Part of <https://github.com/stackabletech/issues/issues/647>

### Update pre-commit Workflow

> [!NOTE]
> The pre-commit config and workflows need to be kept up-to-date to ensure
> usage of recent tooling versions. This requires some manual work in this
> repository.

```[tasklist]
### Tasks
- [x] Update `python-version` in local and templated `pr_pre-commit.yml` workflow (Not applicable, continue to use 3.12)
- [x] Update hook refs in local and templated `.pre-commit-config.yaml` file
- [x] Update Hadolint version in the `config/versions.yaml` file (Already on latest: 2.12.0)
- [ ] https://github.com/stackabletech/operator-templating/pull/451
```

### Update Rust Toolchain (1.81.0)

> [!NOTE]
> During a Stackable release we need to ensure that every product operator uses
> the latest Rust toolchain (used by us). To keep the toolchain in sync across
> all our operators, we update the version centrally in this repository.

```[tasklist]
### Tasks in this Repository
- [x] Update Rust toolchain in the `config/versions.yaml` file.
- [ ] https://github.com/stackabletech/operator-templating/pull/452
- [x] Generate downstream PRs using the ["Generate Downstream PRs"](https://github.com/stackabletech/operator-templating/actions/workflows/generate_prs.yml) action.
- [x] Merge downstream PRs, see below for more details.
```

Replace the items in the task lists below with the applicable Pull Requests

```[tasklist]
### Tasks in Downstream Operator Repositories
- [ ] https://github.com/stackabletech/airflow-operator/pull/521
- [ ] https://github.com/stackabletech/commons-operator/pull/291
- [ ] https://github.com/stackabletech/druid-operator/pull/639
- [ ] https://github.com/stackabletech/edc-operator/pull/131
- [ ] https://github.com/stackabletech/hbase-operator/pull/576
- [ ] https://github.com/stackabletech/hdfs-operator/pull/593
- [ ] https://github.com/stackabletech/hello-world-operator/pull/126
- [ ] https://github.com/stackabletech/hive-operator/pull/524
- [ ] https://github.com/stackabletech/kafka-operator/pull/774
- [ ] https://github.com/stackabletech/listener-operator/pull/239
- [ ] https://github.com/stackabletech/nifi-operator/pull/696
- [ ] https://github.com/stackabletech/opa-operator/pull/639
- [ ] https://github.com/stackabletech/secret-operator/pull/511
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/481
- [ ] https://github.com/stackabletech/superset-operator/pull/550
- [ ] https://github.com/stackabletech/trino-operator/pull/656
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/873
```

**Comment by Techassi** [comment]
Completed.
